from cellquantifier.segm import *
from glob import glob
from skimage.util import img_as_ubyte
from skimage.io import imread, imsave

"""

U-Net

This application builds the u-net architecture to perform automated segmentation
of raw image data. Modify default paths and comment out lines for your purposes.

Notes
----------

1. Every image to used for training should be accompanied by a mask with an
   identical file name and '.png' type

2. To perform segmentation w/o training a new model, use the u-net wrapper
   function cellquantifier.segm.segm_unet() and pass a custom model or use
   one of the default cellquantifier models

3. If training and using a new custom model, the suggested directory structure is

    /unet
        /train_input - contains raw image + masks for training
            /raw - raw image data
            /target - ground truth masks
        /test_input - contains raw image data to be segmented
        /test_output - contains masks predicted by the model
        (model.h5) - generated by cellquantifier
        (train_stats.csv) - generated by cellquantifier

"""

# """
# ~~~~~~~~~~~I/O~~~~~~~~~~~~~~
# """

root_dir = '/home/cwseitz/unet/'
train_dir  = root_dir + 'train_input/'
test_dir = root_dir + 'test_input/'

# """
# ~~~~~~~~~~~Train~~~~~~~~~~~~~~
# """

#
# crop_size = (256, 256)
# input, target = read_train_files(train_dir, crop_size=crop_size)
#
# build_new_model(input,
#                 target,
#                 crop_size,
#                 save_dir=root_dir,
#                 epochs=100)


# """
# ~~~~~~~~~~~Test~~~~~~~~~~~~~~
# """

files = glob(test_dir + '/*.tif')
stack = imread(files[0]); stack = stack[:10]
stack = stack/stack.max()

dim1, dim2 = stack.shape[1], stack.shape[2]
model = unet_model(input_size=(dim1, dim2))
weights = model.load_weights(root_dir + 'model.h5')
make_prediction(stack, weights, output_path=root_dir + 'test_output/')
